Develop
Gremuar/JavaDevelop_Education_HomeWork pull request #2
Opened 2020-10-23 14:33 UTC by Gremuar

Добавлены ДЗ 5, 6

2020-11-01 00:55 UTC, runnerpeople requested changes
```
Starting audit...
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:1:9: Package name 'ru.home_work.work_2' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:7:16: Variable 'width' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:8:16: Variable 'height' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:9:19: Variable 'msg' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:28:33: Parameter name 'w' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [ParameterName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:28:40: Parameter name 'h' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [ParameterName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:28:50: Parameter name 't' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [ParameterName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:29:13: Local variable name 'tLineNum' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [LocalVariableName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_2/PrintBorderedMessage.java:33:16: Local variable name 'tLine' must match pattern '^[a-z][a-z0-9][a-zA-Z0-9]*$'. [LocalVariableName]
Audit done.
Checkstyle ends with 9 errors.
geoiva@MacBook-Pro-Georgij SberJava % java -jar checkstyle-8.26-all.jar -c sber_checkstyle.xml students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_3/ArrayReverse.java 
Starting audit...
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_3/ArrayReverse.java:1:9: Package name 'ru.home_work.work_3' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_3/ArrayReverse.java:11: Comment has incorrect indentation level 0, expected is 4, indentation should be the same level as line 12. [CommentsIndentation]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_3/ArrayReverse.java:24: 'if' construct must use '{}'s. [NeedBraces]
Audit done.
Checkstyle ends with 3 errors.
geoiva@MacBook-Pro-Georgij SberJava % java -jar checkstyle-8.26-all.jar -c sber_checkstyle.xml students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/        
Starting audit...
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/Bear.java:1:9: Package name 'ru.home_work.work_4.zoo.animal' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/Bear.java:4:20: Variable 'sleep' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/Rabbit.java:1:9: Package name 'ru.home_work.work_4.zoo.animal' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/Gull.java:1:9: Package name 'ru.home_work.work_4.zoo.animal' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/Gull.java:4:20: Variable 'fly' must be private and have accessor methods. [VisibilityModifier]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:1:9: Package name 'ru.home_work.work_4.zoo.animal' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:25:9: 'for' is not followed by whitespace. [WhitespaceAfter]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:25:9: WhitespaceAround: 'for' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:26: 'if' construct must use '{}'s. [NeedBraces]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:26:13: 'if' is not followed by whitespace. [WhitespaceAfter]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:26:13: WhitespaceAround: 'if' is not followed by whitespace. Empty blocks may only be represented as {} when not part of a multi-block statement (4.1.3) [WhitespaceAround]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:35: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:38: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:41: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:44: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:47: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:50: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/animal/BaseAnimal.java:53: 'METHOD_DEF' should be separated from previous statement. [EmptyLineSeparator]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rustam_dzafarov/JavaDevelop_Education_HomeWork/src/ru/home_work/work_4/zoo/App.java:1:9: Package name 'ru.home_work.work_4.zoo' must match pattern '^[a-z]+(\.[a-z][a-z0-9]*)*$'. [PackageName]
[ERROR] /Users/geoiva/Desktop/SberJava/students/rusta [...]

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/App.java
> +package ru.home_work.work_5_6.zoo;
Подправь имя пакета, пожалуйста. Без _

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/animal/Bear.java
> +    public void fishing() {
А почему не вынес в интерфейс?

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +    private ArrayList<BaseAnimal> list = new ArrayList<>();
Почему использована данная коллекция для хранения животных?

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +    private Integer curr = 0;
Зачем использовать эту переменную, если у нас есть метод size у коллекций?

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +        return this;
Интересный подход.
Но рекомендую возвращать true/false в зависимости от успешности операции

2020-11-01 00:55 UTC, runnerpeople commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +        return this;
Здесь лучше сделать функцию void

2020-11-01 12:02 UTC, merged

2020-11-05 13:55 UTC, Gremuar commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +    private ArrayList<BaseAnimal> list = new ArrayList<>();
На данном этапе было не столь важно какую использовать. ArrayList наиболее ближе ассоциируется у меня с массивом и мне удобнее было в нем хранить объекты.

2020-11-05 14:03 UTC, Gremuar commented on src/ru/home_work/work_5_6/zoo/animal/Aviary.java
> +    private Integer curr = 0;
По большому счету незачем, просто захотелось повводить лишних сущностей, почему бы и нет)